"""Added link for payment

Revision ID: 81ef7b5824d4
Revises: e8675ee364b0
Create Date: 2025-10-14 21:11:53.490425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ef7b5824d4'
down_revision: Union[str, Sequence[str], None] = 'e8675ee364b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('external_payment_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'external_payment_link')
    # ### end Alembic commands ###
